### PR TITLE
Infrastructure for JOSS paper

### PR DESCRIPTION
**Pull request by dfm**
Work in progress - don't merge!

### CODE REVIEW

**Comment by dfm** [comment]
OK this is ready. It uses GitHub actions to compile the JOSS paper and makes a `joss-paper` branch. For example: https://github.com/dfm/mapping_stellar_surfaces/blob/joss-pdf/joss/paper.pdf

**Comment by rodluger** [comment]
Thanks! How hard would it be to generate some figures within this build?

**Comment by dfm** [comment]
Should be easy enough. Point me to the scripts and I'll set it up.

**Comment by dfm** [comment]
One point though: I think that the JOSS paper should probably be *in* the starry_process repo. It's allowed to be on a branch, but it is required to be in the repo for the software it is describing. I can open this PR there instead?

**Comment by rodluger** [comment]
Ah, gotcha. Yes, move the PR over. I'll move the scripts over and ping you.

**Comment by rodluger** [comment]
@dfm the figures are in `joss/figures` in the `starry_process` repo.

**Pull request closed without merging**
